routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('admin.dashboard');

Route::group(['prefix' => 'Inventory','namespace'=>'Inventory'], function () {
    Route::resource('/category', 'CategoryController');
    Route::resource('/supplier', 'SupplierController');
    Route::resource('/supplier-product', 'SupplierProductController');
    Route::resource('/purchase', 'PurchaseController');
    Route::get('/purchase-item/{id}','PurchaseController@supplierItem')->name('supplier.item');
    
    Route::get('/customer/credit','CustomerController@creditCustomer')->name('customer.creditCustomer');
    Route::resource('/customer', 'CustomerController');
    Route::get('/customer-paid','CustomerController@paidCustomer')->name('customer.paidCustomer');
    Route::get('/product','PurchaseController@products')->name('product.index');
    Route::resource('/sell', 'SellController');
    Route::get('/product-get/{name}','SellController@getProduct');
    Route::get('/sell-paid','SellController@getPaid')->name('sell.paid');
    Route::get('/sell-due','SellController@getDue')->name('sell.due');
   
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function products(){
        return $this->hasMany('App\SupplierProduct');
    }
}

app/Http/Controllers/Inventory/CategoryController.php
<?php

namespace App\Http\Controllers\Inventory;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['categories'] = Category::all();
        return view('admin.pages.category.category',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $request->validate([
           'cat_name'=>'required'
       ]);
       $category = new Category;

       $category->cat_name = $request->cat_name;
       $category->save();
       return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        dd($id);
        $data['category'] = Category::find($id);
        dd($data['category']);
        return view('admin.pages.category.category',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    //    dd($request->all());
       $request->validate([
        'cat_name'=>'required'
    ]);
    $category =  Category::find($id);
    $category->cat_name = $request->cat_name;
    $category->save();
    return redirect()->back();   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        $category =  Category::find($id);
        $category->delete();
        return redirect()->back();  
    }
}

resources/views/admin/pages/category/category.blade.php
@extends('home')
@section('content')
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="offset-3 col-md-6 mt-3">
                    <!-- general form elements -->
                    <div class="card card-primary">
                      <div class="card-header">
                        <h3 class="card-title">Create Category</h3>
                      </div>
                      <!-- /.card-header -->
                      <!-- form start -->
                     <form role="form" action="{{route('category.store')}}" method="POST">
                          @csrf
                        <div class="card-body">
                          <div class="form-group">
                            <label for="exampleInputEmail1">Category name</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" name="cat_name">
                          </div>
                        </div>
                        <!-- /.card-body -->
        
                        <div class="card-footer">
                          <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                      </form>
                    </div>
                    <!-- /.card -->
                  </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                          <h3 class="card-title">Categories Table</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                          <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                              <th>serial</th>
                              <th>Category Name</th>
                              <th>Action</th>
                             
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($categories as $key => $category)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$category->cat_name}}
                                </td>
                                <td>
                                <a href="" data-id="{{$category->id}}" class="btn btn-success float-left mr-2 editModalBtn" data-toggle="modal" data-target="#exampleModalCenter{{$category->id}}" >Edit</a>
                                    {{-- data-toggle="modal" data-target="#exampleModalCenter" --}}
                                <form action="{{route('category.destroy',$category->id)}}" method="POST">
                                  @csrf
                                  @method("DELETE")
                                          <button class="btn btn-danger" onclick="return confirm('are you sure ?')">Delete</button>
                                    </form>
                                </td>
                              </tr>


                               <!-- Modal -->
              <div class="modal fade" id="exampleModalCenter{{$category->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLongTitle">Update Category</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                  <form action="{{route('category.update',$category->id)}}" method="POST">
                    @csrf
                    @method('PUT')
                      <div class="modal-body">
                        <div class="form-group">
                          <label for="exampleInputEmail1">Category name</label>
                        <input type="text" class="form-control" id="cat_name" name="cat_name" value="{{$category->cat_name}}">
                        </div>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Update</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
                            @endforeach
                           
                            </tbody>
                          </table>
                        </div>
                        <!-- /.card-body -->
                      </div>
                </div>
            </div>
            
             
            

        </div>
    </div>
@endsection

@push('js')
    <script>
//       $(document).ready(function() {

//           $.ajaxSetup({

//           headers: {

//               'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')

//           }

//     });
//     $('.editModalBtn').click(function(e) {
//       e.preventDefault();
      
//       // alart('hello');
//       var id=$(this).data('id');
//       // var action ="{{ route('category.edit',"id") }}";
//       var url = '{{ route("category.edit", ":id") }}';
//     	url = url.replace(':id',id);
//       // var url ='{{url("/Inventory/category'+id+'/edit")}}';
//       // var action = url('/Inventory/category/'+id+'/edit');
//       console.log(url);


//       // var url = '{{URL::to('class_routine')}}';
//       $.ajax({
//         type : 'GET',
//         url  : url,
//         data : {'id':id},
        
//         success:function(data){

//           // $('#cat_name').val(data.cat_name);
//           console.log(data);
//           // $('.class-id').val(data.class_id);
//           // $('.subject_id').val(data.subject_id);
//           // $('.day_of_week').val(data.day_of_week);
//           // $('.teacher_id').val(data.teacher_id);
//           // $('.start_time').val(data.start_time);
//           // $('.end_time').val(data.end_time);
//           // $('.classFormUpdate').attr('action',action);
//           $('#editModal').modal('show');
//         }
//       });
//     });
// });
    </script>
@endpush