routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('admin.dashboard');

Route::group(['prefix' => 'Inventory','namespace'=>'Inventory'], function () {
    Route::resource('/category', 'CategoryController');
    Route::resource('/supplier', 'SupplierController');
    Route::resource('/supplier-product', 'SupplierProductController');
    Route::resource('/purchase', 'PurchaseController');
    Route::get('/purchase-item/{id}','PurchaseController@supplierItem')->name('supplier.item');
    
    Route::get('/customer/credit','CustomerController@creditCustomer')->name('customer.creditCustomer');
    Route::resource('/customer', 'CustomerController');
    Route::get('/customer-paid','CustomerController@paidCustomer')->name('customer.paidCustomer');
    Route::get('/product','PurchaseController@products')->name('product.index');
    Route::resource('/sell', 'SellController');
    Route::get('/product-get/{name}','SellController@getProduct');
    Route::get('/sell-paid','SellController@getPaid')->name('sell.paid');
    Route::get('/sell-due','SellController@getDue')->name('sell.due');
   
});

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    public function supplierProducts()
    {
      return $this->belongsToMany('App\SupplierProduct');
    }
    public function Purchases(){
      return $this->hasMany('App\Purchase');
  }
}

app/Http/Controllers/Inventory/SupplierController.php
<?php

namespace App\Http\Controllers\Inventory;

use App\Supplier;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['suppliers']= Supplier::all();
        return view('admin.pages.supplier.allSupplier',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.supplier.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $request->validate([

        "name"=>'required',
        "mobile"=>'required',
        "address"=>'required',
        "details"=>'required'

       ]);

       $supplier = new Supplier;
       $supplier->name = $request->name;
       $supplier->mobile = $request->mobile;
       $supplier->address = $request->address;
       $supplier->details = $request->details;
       $supplier->save();
       return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            "name"=>'required',
            "mobile"=>'required',
            "address"=>'required',
            "details"=>'required|max:500'
    
           ]);
    
           $supplier = Supplier::find($id);
           $supplier->name = $request->name;
           $supplier->mobile = $request->mobile;
           $supplier->address = $request->address;
           $supplier->details = $request->details;
           $supplier->save();
           return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $supplier = Supplier::find($id);
        $supplier->delete();
        return redirect()->back();

    }
}

resources/views/admin/pages/supplier/allSupplier.blade.php
@extends('home')
@section('content')
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                          <h3 class="card-title">All Suppliers</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                          <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                              <th>serial</th>
                              <th>Supplier Name</th>
                              <th>Mobile</th>
                              <th>Address</th>
                              <th>Details</th>
                              <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($suppliers as $key => $supplier)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$supplier->name}}</td>
                                <td>{{$supplier->mobile}}</td>
                                <td>{{$supplier->address}}</td>
                                <td>{{$supplier->details}}</td>
                                <td>
                                <a href="" data-id="{{$supplier->id}}" class="btn btn-success float-left mr-2 editModalBtn" data-toggle="modal" data-target="#exampleModalCenter{{$supplier->id}}" >Edit</a>
                                    {{-- data-toggle="modal" data-target="#exampleModalCenter" --}}
                                <form action="{{route('supplier.destroy',$supplier->id)}}" method="POST">
                                  @csrf
                                  @method("DELETE")
                                          <button class="btn btn-danger" onclick="return confirm('are you sure ?')">Delete</button>
                                    </form>
                                </td>
                              </tr>
                               <!-- Modal -->
              <div class="modal fade" id="exampleModalCenter{{$supplier->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLongTitle">Update Category</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <form role="form" action="{{route('supplier.update',$supplier->id)}}" method="POST">
                      @csrf
                      @method("PUT")
                    <div class="card-body">
                      <div class="form-group">
                        <label for="exampleInputEmail1">Supplier Name</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" value="{{$supplier->name}}" name="name">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Mobile</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" value="{{$supplier->mobile}}" name="mobile">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Address</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" value="{{$supplier->address}}" name="address">
                      </div>
                      <div class="form-group">
                        <label for="">Details</label>
                        <textarea class="form-control" name="details" id="" rows="3">{{$supplier->details}}</textarea>
                      </div>
                    </div>
                    <!-- /.card-body -->
    
                    <div class="card-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </form>
                  </div>
                </div>
              </div>
                            @endforeach
                           
                            </tbody>
                          </table>
                        </div>
                        <!-- /.card-body -->
                      </div>
                </div>
            </div>
            
             
            

        </div>
    </div>
@endsection

@push('js')
    <script>
//       $(document).ready(function() {

//           $.ajaxSetup({

//           headers: {

//               'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')

//           }

//     });
//     $('.editModalBtn').click(function(e) {
//       e.preventDefault();
      
//       // alart('hello');
//       var id=$(this).data('id');
//       // var action ="{{ route('category.edit',"id") }}";
//       var url = '{{ route("category.edit", ":id") }}';
//     	url = url.replace(':id',id);
//       // var url ='{{url("/Inventory/category'+id+'/edit")}}';
//       // var action = url('/Inventory/category/'+id+'/edit');
//       console.log(url);


//       // var url = '{{URL::to('class_routine')}}';
//       $.ajax({
//         type : 'GET',
//         url  : url,
//         data : {'id':id},
        
//         success:function(data){

//           // $('#cat_name').val(data.cat_name);
//           console.log(data);
//           // $('.class-id').val(data.class_id);
//           // $('.subject_id').val(data.subject_id);
//           // $('.day_of_week').val(data.day_of_week);
//           // $('.teacher_id').val(data.teacher_id);
//           // $('.start_time').val(data.start_time);
//           // $('.end_time').val(data.end_time);
//           // $('.classFormUpdate').attr('action',action);
//           $('#editModal').modal('show');
//         }
//       });
//     });
// });
    </script>
@endpush

resources/views/admin/pages/supplier/create.blade.php
@extends('home')
@section('content')
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="offset-3 col-md-6 mt-3">
                    <!-- general form elements -->
                    <div class="card card-primary">
                      <div class="card-header">
                        <h3 class="card-title">Create Supplier</h3>
                      </div>
                      <!-- /.card-header -->
                      <!-- form start -->
                     <form role="form" action="{{route('supplier.store')}}" method="POST">
                          @csrf
                        <div class="card-body">
                          <div class="form-group">
                            <label for="exampleInputEmail1">Supplier Name</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" name="name">
                          </div>
                          <div class="form-group">
                            <label for="exampleInputEmail1">Mobile</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" name="mobile">
                          </div>
                          <div class="form-group">
                            <label for="exampleInputEmail1">Address</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" name="address">
                          </div>
                          <div class="form-group">
                            <label for="">Details</label>
                            <textarea class="form-control" name="details" id="" rows="3"></textarea>
                          </div>
                        </div>
                        <!-- /.card-body -->
        
                        <div class="card-footer">
                          <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                      </form>
                    </div>
                    <!-- /.card -->
                  </div>
            </div>
        </div>
    </div>
@endsection